---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  annotations:
    what-do-you-like: crash-with-error-500
  name: liveness-http
spec:
  containers:
  - name: i-am-alive
    image: gcr.io/google_containers/liveness
    args:
    - /server
