---
apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
  annotations:
    i-will-crash: after-5-calls-to-slash
spec:
  containers:
    - image: luksa/kubia-unhealthy
      name: kubia
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        periodSeconds: 5
