---
apiVersion: apps/v1 # Utiliser 'apps/v1' à partir de Kubernetes v1.9, sinon apps/v1beta2
kind: ReplicaSet
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      env: qlf
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
        env: int
    spec:
      containers:
      - name: nginx-fe
        image: nginx:alpine
        ports:
        - containerPort: 80
