---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      env: int
  template:
    metadata:
      labels:
        app: frontend
        env: int
    spec:
      containers:
      - name: nginx-fe
        image: nginx:alpine
        ports:
        - containerPort: 80
