---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-rebirth
  labels:
    app: frontend
    env: int
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      env: int
#    matchExpressions:
#      - key: env
#        operator: In
#        values:
#          - int
  template:
    metadata:
      labels:
        app: frontend
        env: int
    spec:
      containers:
      - name: nginx-fe-4-rs
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
