---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: second-pv
spec:
  capacity:
    storage: 600Mi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/pv/pv004
