---
apiVersion: v1
kind: Pod
metadata:
  labels:
    my-label: cool
    env: rd
  name: centos-pod-with-labels
spec:
  restartPolicy: Always
  terminationGracePeriodSeconds: 2
  containers:
    - image: centos:7
      imagePullPolicy: Always
      name: shelly
      command:
        - "bash"
        - "-c"
        - "sleep infinity"
