---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "filter.fullname" . }}
  labels:
    app: {{ template "guestbook.name" . }}
    component: filter
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.filterReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "guestbook.name" . }}
        component: filter
        release: {{ .Release.Name }}
      annotations:
        io.nodevops/rely-on-confd: "no"
    spec:
      containers:
        - name: &mainContainerName filter
          image: looztra/guestbook-filter:{{ default .Values.image.mainVersion .Values.image.filterVersion }}-aio
          ports:
            - name: main
              containerPort: 8080
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
              readOnly: false
          livenessProbe:
            httpGet:
              path: /admin/info
              port: 8080
            initialDelaySeconds: {{ default .Values.initialDelaySeconds.shared .Values.initialDelaySeconds.filter }}
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /admin/info
              port: 8080
            initialDelaySeconds: {{ default .Values.initialDelaySeconds.shared .Values.initialDelaySeconds.filter }}
            timeoutSeconds: 1
            failureThreshold: 3
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
