---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "filter.fullname" . }}
  labels:
    app: {{ template "guestbook.name" . }}
    component: storage
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "guestbook.name" . }}
    component: filter
  ports:
    - name: main
      port: 8080
      targetPort: main
      protocol: TCP
