---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: whoami
spec:
  replicas: 5
  selector:
    matchLabels:
      app: whoami
      env: int
  template:
    metadata:
      labels:
        app: whoami
        env: int
    spec:
      containers:
      - image: containous/whoami:latest
        name: whoami
        ports:
        - name: main-port
          containerPort: 80
